name: 'E2E Tests'

on:
  push:
    branches: [v3.x-bundle]
    paths-ignore:
      - '**/*.md'
  # pull_request:
  #   branches: [ main ]
  #   paths-ignore:
  #     - '**/*.md'

env:
  pnpm_version: 8
  node_version: 20
  debug_identifier: nammatham:*

  RESOURCE_IDENTIFIER_NODE18_LINUX_X64: ${{ secrets.RESOURCE_IDENTIFIER_NODE18_LINUX_X64 }}

jobs:
  get-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.deploy-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.node_version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ env.pnpm_version }}

      - run: pnpm install
      - name: Export the matrix for testing
        id: deploy-matrix
        run: pnpm exec nx run @infra/azure-functions:github-actions

  build:
    runs-on: ${{ matrix.os }}
    needs: get-matrix
    strategy:
      matrix:
        include: ${{fromJson(needs.get-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        if: matrix.runtime == 'bun'

      - name: Use Node.js ${{ matrix.version }}
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: ${{ env.pnpm_version }}
      - run: pnpm install
      
      - run: pnpm build

      - name: pnpm install again for ensure the cli is available
        run: pnpm install

      - name: Build the project
        run: pnpm exec nx run @examples/with-${{ matrix.runtime }}:build
        env: 
          DEBUG: ${{ env.debug_identifier }}
